###
GET http://localhost:8080/api/speedrenthu/orders/machine/2
Accept: application/json


###
GET http://localhost:8080/api/speedrenthu/orders//revenue_by_segment
Accept: application/json


###
GET http://localhost:8080/api/speedrenthu/orders/machine/1/revenue
Accept: application/json


###
POST http://localhost:8080/api/speedrenthu/orders
Content-Type: application/json

{
  "name": "vibrating temper",
  "duration": "THREE_HOURS",
  "date": "2021-07-06",
  "location": "Budapest"
}

###
PUT http://localhost:8080/api/speedrenthu/orders/2
Content-Type: application/json

{
  "status": "CANCELED"
}

###
DELETE http://localhost:8080/api/speedrenthu/orders
Content-Type: application/json

{
  "date": "2021-07-10"
}
###

DELETE http://localhost:8080/api/speedrenthu/orders/11
Accept: application/json6


}
###